-- V8：task_events.type 增加 ACTIVITY（OBS-1 观测活动事件）
ALTER TABLE task_events DROP CONSTRAINT chk_events_type;
ALTER TABLE task_events ADD CONSTRAINT chk_events_type CHECK (type IN
    ('CREATED','DISPATCHED','LEASE_EXPIRED','STAGE_STARTED','STAGE_COMPLETED',
     'RETRY','BUDGET_EXCEEDED','SUCCEEDED','FAILED','CANCELLED','WEBHOOK_SENT',
     'ACTIVITY'));
